Updated paper 15 for Avatars by adding the code repo link of v2 and their new title.
MrNeRF/awesome-3D-gaussian-splatting pull request #136
Opened 2024-06-12 20:59 UTC by ElenaViewSynthesis

See descriptions of my 2 previous commit changes

2024-06-12 21:55 UTC, MrNeRF requested changes
Thx for your contribution. Please see my comment

2024-06-12 21:55 UTC, MrNeRF commented on README.md
> +
Thank you for your contribution. I am just wonder why we should present both versions? I would suggest the latest is the greatest and would remove the old one? The rest looks great!

2024-06-13 17:30 UTC, ElenaViewSynthesis reviewed
Yes, we should only keep the latest version.

2024-06-13 18:28 UTC, merged

2024-06-13 18:28 UTC, MrNeRF commented
Thank you :)