add LoopSplat in SLAM
MrNeRF/awesome-3D-gaussian-splatting pull request #182
Opened 2024-10-04 18:56 UTC by Zhu-Liyuan

https://loopsplat.github.io/

2024-10-05 12:58 UTC, MrNeRF requested changes

2024-10-05 12:58 UTC, MrNeRF commented on README.md
> +[📄 Paper](https://arxiv.org/abs/2408.10154) | [🌐 Project Page](https://loopsplat.github.io/) | [💻 Code](https://github.com/GradientSpaces/LoopSplat)
Can you please add an empty line after your changes and remove on before your entry?

2024-10-05 12:59 UTC, MrNeRF commented
Thx for your contribution. Just a small change request before I merge.

2024-10-05 21:15 UTC, Zhu-Liyuan commented
I've made the requested formatting changes. Please review. Thanks!

2024-10-06 07:31 UTC, MrNeRF commented
Thank you!

2024-10-06 07:31 UTC, merged